#!/bin/bash
set -eu

YELLOW="\e[33m"
BLUE="\e[34m"
STOP="\e[0m"
PRIMARY=$YELLOW
SECONDARY=$BLUE

printf "\n"
printf "${SECONDARY}┏━━━ ${PRIMARY}Select a Code Sample${SECONDARY} ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n"
printf "${SECONDARY}┃                                                                             ┃\n"
printf "${SECONDARY}┃${PRIMARY}   1. 👋  Hello, World! ${SECONDARY}src-examples/Examples/HelloWorld.elm . (elm-html)    ┃\n"
printf "${SECONDARY}┃                                                                             ┃\n"
printf "${SECONDARY}┃${PRIMARY}   2. ⏳  Counter ${SECONDARY}..... src-examples/Examples/Counter.elm .... (elm-html)    ┃\n"
printf "${SECONDARY}┃                                                                             ┃\n"
printf "${SECONDARY}┃${PRIMARY}   3. ⏳  Counter ${SECONDARY}..... src-examples/Examples/CounterElmUi.elm (elm-ui)      ┃\n"
printf "${SECONDARY}┃                                                                             ┃\n"
printf "${SECONDARY}┃${PRIMARY}   4. 🌐  Geolocation ${SECONDARY}. src-examples/Examples/Geolocation.elm  (elm-http)    ┃\n"
printf "${SECONDARY}┃                                                                             ┃\n"
printf "${SECONDARY}┃${PRIMARY}   5. ♦️   Cards ${SECONDARY}....... src-examples/Examples/Cards.elm ...... (elm-random)  ┃\n"
printf "${SECONDARY}┃                                                                             ┃\n"
printf "${SECONDARY}┃${PRIMARY}   6. ⏰  Clock ${SECONDARY}....... src-examples/Examples/Clock.elm ...... (elm-time)    ┃\n"
printf "${SECONDARY}┃                                                                             ┃\n"
printf "${SECONDARY}┃${PRIMARY}   7. 📝  Todos ${SECONDARY}....... src-examples/Examples/Todos.elm ...... (ports)       ┃\n"
printf "${SECONDARY}┃                                                                             ┃\n"
printf "${SECONDARY}┃${PRIMARY}   8. 💻  SPA ${SECONDARY}......... src-examples/SPA.elm ................. (ports)       ┃\n"
printf "${SECONDARY}┃                                                                             ┃\n"
printf "${SECONDARY}┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\n"
printf "${PRIMARY}\n"
read -p "Example number: " EXAMPLE
DEMO=${EXAMPLE:-"_"}
printf "\n"

if   [ $EXAMPLE == "1" ]; then
    cmd/serve src-examples/Examples/HelloWorld.elm
elif [ $EXAMPLE == "2" ]; then
    cmd/serve src-examples/Examples/Counter.elm
elif [ $EXAMPLE == "3" ]; then
    cmd/serve src-examples/Examples/CounterElmUi.elm
elif [ $EXAMPLE == "4" ]; then
    cmd/serve src-examples/Examples/Geolocation.elm
elif [ $EXAMPLE == "5" ]; then
    cmd/serve src-examples/Examples/Cards.elm
elif [ $EXAMPLE == "6" ]; then
    cmd/serve src-examples/Examples/Clock.elm
elif [ $EXAMPLE == "7" ]; then
    cmd/serve src-examples/Examples/Todos.elm
elif [ $EXAMPLE == "8" ]; then
    cmd/serve src-examples/SPA.elm
else
    printf "Demo ${DEMO} not found\n\n"    
fi
